version: "3.1"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: always
    ports:
      - 38000:80
    volumes:
      - /volume2/docker/vaultwarden:/data
    environment:
      - TZ=Asia/Seoul
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN={Admin_Password} #관리자용암호 https://[domain]/admin
