version: "3"

services:
  db:
    container_name: { postgres-mattermost }
    image: postgres:latest
    ports:
      - { "5432:5432" }
    restart: unless-stopped
    volumes:
      - { /volume2/docker/postgres:/var/lib/postgresql/data:rw }
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER={admin}
      - POSTGRES_PASSWORD={admin}
      - POSTGRES_DB={mattermost}

  app:
    container_name: { mattermost }
    image: mattermost/mattermost-team-edition:latest
    ports:
      - { "8065:8065" }
    restart: unless-stopped
    volumes:
      - { /volume2/docker/mattermost/config:/mattermost/config:rw }
      - { /volume2/docker/mattermost/data:/mattermost/data:rw }
      - { /volume2/docker/mattermost/logs:/mattermost/logs:rw }
      - { /volume2/docker/mattermost/plugins:/mattermost/plugins:rw }
      - {
          /volume2/docker/mattermost/client/plugins:/mattermost/client/plugins:rw,
        }
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME={admin}
      - MM_PASSWORD={admin}
      - MM_DBNAME={mattermost}
      - MM_SQLSETTINGS_DATASOURCE=postgres://{admin}:{admin}@db:{5432}/{mattermost}?sslmode=disable&connect_timeout=10
