version: '3.7'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    env_file:
      - ${DOCKER_DATA}/palworld/default.env
    volumes:
      - ${DOCKER_DATA}/palworld:/palworld
    environment:
      - TZ=Asia/Seoul