version: "3"

services:
  nginx-proxy-manager:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8443:443"
      - "8080:80"
      - "81:81"
    restart: unless-stopped
    volumes:
      - /volume2/docker/nginx-proxy-manager/data:/data:rw
      - /volume2/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:rw
    environment:
      - TZ=Asia/Seoul
