services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: always
    ports:
      - 38000:80
    volumes:
      - ${DOCKER_DATA}/vaultwarden:/data
    environment:
      - TZ=Asia/Seoul
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN={ADMIN_PW} #관리자용암호 https://[domain]/admin