version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
      - 51080:9000  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DOCKER_DATA}/portainer:/data
    environment:
      - TZ=Asia/Seoul